version: '3'

volumes:
  db-data:


services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails webpacker:install && rails webpacker:compile && rake db:create && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/myapp'
    environment:
      - 'DB_PASSWORD=${DB_PASSWORD}'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
    networks:
      - internal
      - external

  db:
    image: postgres:12
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    networks:
      - internal

networks:
  internal:
    internal: true
  external:
    name: web_network
